### ISSUE TITLE
"Incorrect Padding" error when trying to decode some strings

### ISSUE THREAD

**Issue by x-42** [x-42/baserot#1]
This happens when a base64 string has been encoded but doesn't contain any "=" char at the end of the string. 

for instance: 

a BASEROT encoded string of "q2uuqPO0nTHoJmOg" ("what the"), generates this error upon decoding:

Encode[1] or Decode[2]?
> 2
Enter a BASEROT string to decode> q2uuqPO0nTHoJmOg
[MESSAGE DECODED] ==>
Traceback (most recent call last):
  File "./baserot.py", line 54, in <module>
    print x.b + "[MESSAGE DECODED] ==> ", base64.b64decode(line)
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

current solution is to add a character or two at the end of your original text, i.e., 

"what the!", which generates a BASEROT of "q2uuqPO0nTHuT1fjoD=="

which is then, properly decoded:

Encode[1] or Decode[2]?
> 2
Enter a BASEROT string to decode> q2uuqPO0nTHuT1fjoD==
[MESSAGE DECODED] ==>  what the!

will probably fix this by appending some padding to the initial base64 encoding and then removing it upon decode.

**Comment by x-42** [comment]
added padding to the encode, cleaned up the output.
